version: 2

run:
  timeout: 2m

issues:
  exclude-use-default: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign

linters-settings:
  revive:
    ignore-generated-header: true

  depguard:
    list-type: blacklist
    packages:
      - fmt
    packages-with-error-message:
      fmt: "Use a logger instead of fmt"
