# Config for Air live-reloading during development
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "frontend"]
exclude_file = []
follow_symlink = true
delay = 1000
log = "air.log"

[log]
color = "true"
timestamp = "false"

[misc]
clean_on_exit = true
