run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - errcheck
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - revive
    - unused

issues:
  max-same-issues: 5
  exclude-use-default: false

build-tags:
  - tools
