version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lamina_db_1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lamina_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "/app/server"]
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./wait-for-it.sh
        target: /wait-for-it.sh
        read_only: true

  migrate:
    build:
      context: .
      dockerfile: docker/migrate.Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "migrate", "-path", "/app/migrations", "-database", "${DATABASE_URL}", "up"]
    volumes:
      - ./migrations:/app/migrations
      - ./wait-for-it.sh:/wait-for-it.sh

volumes:
  postgres_data:

