name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test & Lint on Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20', '1.21.6', 'stable']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Print Go Version
        run: go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests with Coverage
        run: |
          go test ./... -v -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Upload Coverage to Codecov (optional)
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
          fail_ci_if_error: false

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.54.2
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run ./... --timeout=5m
